  export default {
    async fetch(request, env, ctx) {
      const url = new URL(request.url);
      // If the request is for a file that exists in the built `public` folder, let
  the static handler serve it
      if (url.pathname.startsWith('/assets/') || url.pathname === '/') return
  fetch(request);
      // Otherwise rewrite to index.html
      return new Response(fetch('index.html', {headers: { 'Content-Type':
  'text/html' } }));
    }
  };
